import {
	defineConfig,
	minimal2023Preset as preset,
} from "@vite-pwa/assets-generator/config";

/**
 * Mirrors `--signal-yellow` in packages/ui/src/styles/tokens.css. Duplicated
 * rather than imported because this config runs in Node at build time, where
 * the stylesheet is not something that can be read for a value.
 */
const SIGNAL_YELLOW = "#ffe01f";

export default defineConfig({
	headLinkOptions: {
		preset: "2023",
	},
	/**
	 * The 2023 preset, with the corner fill changed from white to the tile's
	 * own yellow.
	 *
	 * Every size is generated by fitting the source inside the square and
	 * filling whatever is left over. That default assumes a logo with an
	 * aspect ratio to preserve; ours is already square and already full-bleed,
	 * so the only leftover is the four corners the rounded tile leaves
	 * transparent. White there puts a pale notch outside each corner, and the
	 * platforms that round the icon themselves — iOS on the Apple touch icon,
	 * Android on the maskable one — each use a slightly different radius, so
	 * whether the notch shows is a coin flip per device rather than something
	 * that can be checked once. Filling with the tile colour makes the
	 * question moot: crop it anywhere and the result is yellow.
	 */
	preset: {
		...preset,
		maskable: {
			...preset.maskable,
			resizeOptions: { background: SIGNAL_YELLOW },
		},
		apple: {
			...preset.apple,
			resizeOptions: { background: SIGNAL_YELLOW },
		},
	},
	images: ["public/logo.png"],
});
